# Tag 테이블 Embedding

In [18]:
import pandas as np

In [19]:
from dotenv import load_dotenv
import os

load_dotenv()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

In [20]:
tag_df = np.read_csv("source_csv/tag.csv")
tag_df.head()

  tag_code      name
0  TAG0000    24시간영업
1  TAG0001        회식
2  TAG0002      포장전문
3  TAG0003   이국적/이색적
4  TAG0004  지역주민이 찾는

## Tag to Query

태그를 한 문장의 쿼리로 변환

In [21]:
prompt_tag_to_query = """당신은 식당 검색/추천 시스템을 위한 태그 의미 확장기다.

입력으로 식당의 특징을 나타내는 짧은 태그가 주어진다.
출력은 해당 태그를 임베딩 벡터 생성에 적합한 자연어 문장이다.

목표:
- 짧은 태그를 사용자가 식당을 검색할 때 떠올릴 법한 의미 문장으로 변환한다.
- 식당의 특성, 방문 목적, 이용 상황, 분위기, 운영 방식이 드러나게 쓴다.
- 태그를 단순 반복하지 말고, 실제 검색 의도에 맞게 의미를 풀어쓴다.

규칙:
- 한국어로 작성한다.
- 1~2문장으로 간결하게 작성한다.
- 첫 문장은 태그의 핵심 의미를 식당 특성 중심으로 설명한다.
- 필요하면 두 번째 문장에서 방문 맥락이나 이용 상황을 덧붙인다.
- 광고성 표현, 과장, 주관적 칭찬은 넣지 않는다.
- 태그에 없는 메뉴, 가격, 지역, 업종 정보는 임의로 추가하지 않는다.
- 의미는 풍부하되 불필요하게 장황하지 않게 작성한다.

출력 형식:
- 설명 없이 최종 문장만 하나의 문자열로 출력한다.
- 따옴표 없이 순수 텍스트만 출력한다."""

In [22]:
# from openai import OpenAI

# client = OpenAI(api_key=OPENAI_API_KEY)

# # Chat Completion API 기본 호출
# response = client.chat.completions.create(
#     model='gpt-4o-mini',
#     messages=[
#         {
#             'role': 'system',
#             'content': [
#                 {
#                     'type': 'text',
#                     'text': prompt_tag_to_query
#                 }
#             ]
#         },
#         {
#             'role': 'user',
#             'content': [
#                 {
#                     'type': 'text',
#                     'text': '주차가능'
#                 }
#             ]
#         }
#     ],
#     response_format={
#         'type': 'text'
#     },
#     temperature=1,
#     max_completion_tokens=2048,
#     top_p=1,
#     frequency_penalty=0,
#     presence_penalty=0
# )

# # ChatCompletion(choices=Choice(message=ChatCompletionMessage(content='')))
# print(response.choices[0].message.content)

In [23]:
import os
from openai import OpenAI

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

def analyze_tag(instr: str) -> str:
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {
                "role": "developer",
                "content": prompt_tag_to_query,
            },
            {
                "role": "user",
                "content": instr,
            },
        ],
        temperature=0.3,
        max_completion_tokens=200,
    )

    return response.choices[0].message.content.strip()

In [24]:
import time

tag_list = tag_df["name"].unique()
results = []

ind = 0
for tag in tag_list:
    print(f"{ind}번째 작업중")
    results.append(analyze_tag(tag))
    time.sleep(1)
    ind += 1

print(f"{len(tag_list)} : {len(results)}")
print(results[:3])

0번째 작업중
1번째 작업중
2번째 작업중
3번째 작업중
4번째 작업중
5번째 작업중
6번째 작업중
7번째 작업중
8번째 작업중
9번째 작업중
10번째 작업중
11번째 작업중
12번째 작업중
13번째 작업중
14번째 작업중
15번째 작업중
16번째 작업중
17번째 작업중
18번째 작업중
19번째 작업중
20번째 작업중
21번째 작업중
22번째 작업중
23번째 작업중
24번째 작업중
25번째 작업중
26번째 작업중
27번째 작업중
28번째 작업중
29번째 작업중
30번째 작업중
31번째 작업중
32번째 작업중
33번째 작업중
34번째 작업중
35번째 작업중
36번째 작업중
37번째 작업중
38번째 작업중
39번째 작업중
40번째 작업중
41번째 작업중
42번째 작업중
43번째 작업중
44번째 작업중
45번째 작업중
46번째 작업중
47번째 작업중
48번째 작업중
49번째 작업중
50번째 작업중
51번째 작업중
52번째 작업중
53번째 작업중
54번째 작업중
55번째 작업중
56번째 작업중
57번째 작업중
58번째 작업중
59번째 작업중
60번째 작업중
61번째 작업중
62번째 작업중
63번째 작업중
64번째 작업중
65번째 작업중
66번째 작업중
67번째 작업중
68번째 작업중
69번째 작업중
70번째 작업중
71번째 작업중
72번째 작업중
73번째 작업중
74번째 작업중
75번째 작업중
76번째 작업중
77번째 작업중
78번째 작업중
79번째 작업중
80번째 작업중
81번째 작업중
82번째 작업중
83번째 작업중
84번째 작업중
85번째 작업중
86번째 작업중
87번째 작업중
88번째 작업중
89번째 작업중
90번째 작업중
91번째 작업중
92번째 작업중
93번째 작업중
94번째 작업중
95번째 작업중
96번째 작업중
97번째 작업중
98번째 작업중
99번째 작업중
100번째 작업중
101번째 작업중
102번째 작업중
103번째 작업중
104번째 작업중
105번째 작업중
106번째 작업중
107번째 작업중
108번째 작업중
109번째 작업중
110번째 작업중
111번째 작업중
112번째 작업중
113번째 작업중
114번째 작업중
115번째 작업중
116번째 작업중
117번째 작업중
118번째 작업중
119번째 작업중
120번째 작업중
121번째 작업중
122번째 작업중
123번째 작업중
124번째 작업중
125번째 작업중
126번째 작업중
127번째 작업중
128번째 작업중
129번째 작업중
130번째 작업중
131번째 작업중
132번째 작업중
133번째 작업중
134번째 작업중
135번째 작업중
136번째 작업중
137번째 작업중
138번째 작업중
139번째 작업중
140번째 작업중
141번째 작업중
142번째 작업중
143 : 143
['언제든지 방문할 수 있는 24시간 영업하는 식당으로, 늦은 밤이나 이른 아침에도 편리하게 이용할 수 있는 장소입니다. 다양한 시간대에 맞춰 식사를 원하시는 분들에게 적합합니다.', '직장 동료들과 함께하는 회식에 적합한 식당으로, 넓은 공간과 편안한 분위기를 제공합니다. 다양한 메뉴 선택이 가능해 여러 사람의 입맛을 만족시킬 수 있습니다.', '포장 전문 식당으로, 다양한 메뉴를 편리하게 포장해 집이나 사무실에서 즐길 수 있는 곳입니다. 바쁜 일상 속에서도 맛있는 음식을 간편하게 즐기고 싶은 분들에게 적합합니다.']

In [25]:
mapping = dict(zip(tag_list, results))
tag_df["description"] = tag_df["name"].map(mapping)
tag_df.head()

  tag_code      name                                        description
0  TAG0000    24시간영업  언제든지 방문할 수 있는 24시간 영업하는 식당으로, 늦은 밤이나 이른 아침에도 편...
1  TAG0001        회식  직장 동료들과 함께하는 회식에 적합한 식당으로, 넓은 공간과 편안한 분위기를 제공합...
2  TAG0002      포장전문  포장 전문 식당으로, 다양한 메뉴를 편리하게 포장해 집이나 사무실에서 즐길 수 있는...
3  TAG0003   이국적/이색적  다양한 문화의 맛을 경험할 수 있는 이국적이고 이색적인 식당입니다. 특별한 날이나 ...
4  TAG0004  지역주민이 찾는  지역 주민들이 자주 찾는 식당으로, 편안한 분위기에서 일상적인 식사를 즐길 수 있는...

## Embedding 생성

변환한 쿼리를 embedding 벡터로 변환해서 저장

In [26]:
import base64
import numpy as np
from openai import OpenAI

client = OpenAI(api_key=OPENAI_API_KEY)

def embedding(instr:str) -> str:
    response = client.embeddings.create(
        model='text-embedding-3-small',
        input=[instr, ]
    )
    embedding_vector = response.data[0].embedding

    vec = np.array(embedding_vector, dtype=np.float32)
    blob = vec.tobytes()
    encoded = base64.b64encode(blob).decode('utf-8')

    return encoded

In [27]:
import time

description_list = tag_df["description"].unique()
results = []

ind = 0
for description in description_list:
    print(f"{ind}번째 작업중")
    results.append(embedding(description))
    time.sleep(1)
    ind += 1

print(f"{len(description_list)} : {len(results)}")
print(results[:3])

0번째 작업중
1번째 작업중
2번째 작업중
3번째 작업중
4번째 작업중
5번째 작업중
6번째 작업중
7번째 작업중
8번째 작업중
9번째 작업중
10번째 작업중
11번째 작업중
12번째 작업중
13번째 작업중
14번째 작업중
15번째 작업중
16번째 작업중
17번째 작업중
18번째 작업중
19번째 작업중
20번째 작업중
21번째 작업중
22번째 작업중
23번째 작업중
24번째 작업중
25번째 작업중
26번째 작업중
27번째 작업중
28번째 작업중
29번째 작업중
30번째 작업중
31번째 작업중
32번째 작업중
33번째 작업중
34번째 작업중
35번째 작업중
36번째 작업중
37번째 작업중
38번째 작업중
39번째 작업중
40번째 작업중
41번째 작업중
42번째 작업중
43번째 작업중
44번째 작업중
45번째 작업중
46번째 작업중
47번째 작업중
48번째 작업중
49번째 작업중
50번째 작업중
51번째 작업중
52번째 작업중
53번째 작업중
54번째 작업중
55번째 작업중
56번째 작업중
57번째 작업중
58번째 작업중
59번째 작업중
60번째 작업중
61번째 작업중
62번째 작업중
63번째 작업중
64번째 작업중
65번째 작업중
66번째 작업중
67번째 작업중
68번째 작업중
69번째 작업중
70번째 작업중
71번째 작업중
72번째 작업중
73번째 작업중
74번째 작업중
75번째 작업중
76번째 작업중
77번째 작업중
78번째 작업중
79번째 작업중
80번째 작업중
81번째 작업중
82번째 작업중
83번째 작업중
84번째 작업중
85번째 작업중
86번째 작업중
87번째 작업중
88번째 작업중
89번째 작업중
90번째 작업중
91번째 작업중
92번째 작업중
93번째 작업중
94번째 작업중
95번째 작업중
96번째 작업중
97번째 작업중
98번째 작업중
99번째 작업중
100번째 작업중
101번째 작업중
102번째 작업중
103번째 작업중
104번째 작업중
105번째 작업중
106번째 작업중
107번째 작업중
108번째 작업중
109번째 작업중
110번째 작업중
111번째 작업중
112번째 작업중
113번째 작업중
114번째 작업중
115번째 작업중
116번째 작업중
117번째 작업중
118번째 작업중
119번째 작업중
120번째 작업중
121번째 작업중
122번째 작업중
123번째 작업중
124번째 작업중
125번째 작업중
126번째 작업중
127번째 작업중
128번째 작업중
129번째 작업중
130번째 작업중
131번째 작업중
132번째 작업중
133번째 작업중
134번째 작업중
135번째 작업중
136번째 작업중
137번째 작업중
138번째 작업중
139번째 작업중
140번째 작업중
141번째 작업중
142번째 작업중
143 : 143

In [28]:
mapping = dict(zip(description_list, results))
tag_df["embedding"] = tag_df["description"].map(mapping)
tag_df.head()

,tag_code,name,description,embedding
0,TAG0000,24시간영업,"언제든지 방문할 수 있는 24시간 영업하는 식당으로, 늦은 밤이나 이른 아침에도 편...",AKDGvACg5zgA4MO8AMAgvQAgFz0AQAC9AACLOwAAHT0AIA...
1,TAG0001,회식,"직장 동료들과 함께하는 회식에 적합한 식당으로, 넓은 공간과 편안한 분위기를 제공합...",AGC8OwBg87wAAEi8AEDduwCgwjsAALa8AABPvADAuDwAAE...
2,TAG0002,포장전문,"포장 전문 식당으로, 다양한 메뉴를 편리하게 포장해 집이나 사무실에서 즐길 수 있는...",ACBnPAAAsLwAYCu8AEA5OwDAED0AQA69AAASPACgUz0AIG...
3,TAG0003,이국적/이색적,다양한 문화의 맛을 경험할 수 있는 이국적이고 이색적인 식당입니다. 특별한 날이나 ...,ACCJvABgsbwAoG69AOBgvACgJrsA4Ae9ACCsOwAg6zwAAB...
4,TAG0004,지역주민이 찾는,"지역 주민들이 자주 찾는 식당으로, 편안한 분위기에서 일상적인 식사를 즐길 수 있는...",AOANPACgfTwAgCG9AMD3PACA/DoA4P28AMAavADAMD0AgI...

## 완성한 df를 파일로 저장

설명과 임베딩이 추가된 파일을 db_csv에 저장

In [29]:
tag_df.to_csv("db_csv/tag.csv", index=False)